# koyeb.yaml
version: "1"
name: twrp-builder
services:
  - name: builder
    regions: ["fra"]
    ports:
      - port: 8080
        http_path: /output
    docker:
      image: koyeb/twrp-builder
      build:
        dockerfile: Dockerfile